language: elixir
services:
  - redis-server
env:
  - MIX_ENV=test
matrix:
  include:
    - elixir: 1.5.3
      otp_release: 19.3
    - elixir: 1.5.3
      otp_release: 20.3
    - elixir: 1.6.6
      otp_release: 19.3
    - elixir: 1.6.6
      otp_release: 20.3
    - elixir: 1.6.6
      otp_release: 19.3
    - elixir: 1.6.6
      otp_release: 20.3
    - elixir: 1.6.6
      otp_release: 21.3
    - elixir: 1.7.4
      otp_release: 19.3
    - elixir: 1.7.4
      otp_release: 20.3
    - elixir: 1.7.4
      otp_release: 21.3
    - elixir: 1.7.4
      otp_release: 22.0
    - elixir: 1.8.2
      otp_release: 20.3
    - elixir: 1.8.2
      otp_release: 21.3
    - elixir: 1.8.2
      otp_release: 22.0
    - elixir: 1.8.2
      otp_release: 22.0
      env: MIX_ENV=test LOCKFILE=poison3
    - elixir: 1.8.2
      otp_release: 22.0
      install: skip
      script: mix format --check-formatted --dry-run
      after_script: skip
    - elixir: 1.6.6
      otp_release: 21.0
      before_script: git remote set-branches origin '*' && git fetch origin v1.0.0-compat && git checkout origin/v1.0.0-compat -- test
      env: MIX_ENV=test LABEL=v1.0.0-compat
script: mix coveralls.json
after_script:
  - bash <(curl -s https://codecov.io/bash)
  - MIX_ENV=docs mix deps.get
  - MIX_ENV=docs mix inch.report
